Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-08, with the labels that each got.

#122 Fix room items.
  json/Item_Stack_Roomgoods.txt
Labels: size/XS

#123 EN: A few ability numbers
  json/ChipExplain_SupportExplain.txt
Labels: size/S

#124 EN: New scratch
  json/Item_AvatarWPN_TwinMachineGun.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Roomgoods.txt
Labels: size/XL

#125 Weapon still
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Tact.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/M

#126 EN: New scratch stuff
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_LegFemale.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
Labels: size/L

#127 Fix Tabi gloves.
  json/Item_Stack_BodyPaint.txt
Labels: size/XS

#128 EN: Update SSA names
  json/Explain_Element_UserSkill2.txt
  json/Item_Stack_PaidPass.txt
Labels: size/S

#129 Fix line break spacing.
  json/Item_AvatarWPN_GunSlash.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_Weapon_DoubleSaber.txt
Labels: size/XS

#130 EN: Some chip numbers
  json/ChipExplain_SupportExplain.txt
Labels: size/S

#131 EN: New scratch stuff
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_Sticker.txt
Labels: size/XL

#133 WIP: KO: First work
  README.md
  json/Block_All.txt
  json/Item_Disk_TECWind.txt
  json/Item_QuestTrigger.txt
  json/Item_Stack_Heal.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Tool.txt
  json/Title_All.txt
Labels: size/XXL

#134 KO: boost items
  json/Block_All.txt
  json/Item_RingL.txt
  json/Item_RingR.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_PaidPass.txt
Labels: size/XL

#135 KO: fix typo
  json/Item_Stack_Boost.txt
Labels: size/XS

#136 KO: Translate Items
  json/Explain_System.txt
  json/Item_Pet_CandyCookie.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_GatOMatOther.txt
  json/Item_Stack_Heal.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/XXL

#138 KO: TMG Translation
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/XS

#139 Fix Valentines Chocolate 2: Electric Boogaloo
  json/Item_Stack_Boost.txt
Labels: size/XS
