Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-07, with the labels that each got.

#106 EN: Minor updates
  json/Item_Stack_PaidTicket.txt
  json/Item_Stack_Tool.txt
  json/UI_Text.txt
Labels: size/S

#107 EN: Translate the new titles
  json/Title_All.txt
Labels: size/L

#109 ES: Update
  json/Explain_Element_UserSkill2.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_PaidTicket.txt
  json/Item_Stack_Tool.txt
  json/Title_All.txt
  json/UI_Text.txt
Labels: size/L

#110 RU: Update
  json/Explain_Element_UserSkill2.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_PaidTicket.txt
  json/Item_Stack_Tool.txt
  json/Title_All.txt
  json/UI_Text.txt
Labels: size/L

#108 EN: even more male costumes
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
Labels: size/L

#111 EN: A few updates
  json/ChipExplain_ActiveExplain.txt
  json/UI_Text.txt
Labels: size/M

#112 Translate Sword NT description using OT.
  json/Item_Weapon_Sword.txt
Labels: size/XS

#113 Fix Dalz Soleid's description.
  json/Item_Weapon_Sword.txt
Labels: size/XS

#115 Various fixes.
  json/Item_Stack_PaidPass.txt
  json/Name_Quest_AreaName.txt
Labels: size/XS

#116 Fix typos.
  json/Item_Addon_Unit.txt
  json/Item_AvatarWPN_Partizan.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/M

#119 Update Item_Stack_Headparts.txt
  json/Item_Stack_Headparts.txt
Labels: size/XS

#117 Fix possess typo.
  json/Item_Weapon_DoubleSaber.txt
Labels: size/XS

#118 Fix missing OT-NT descriptions.
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
Labels: size/M

#120 EN: Last week's update
  ChipAndAbilityIDs.txt
  _tools/GaidenEffects.py
  _tools/LinkSkills.py
  json/Awakening_Skill_Explain_Token.txt
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_BoostSkillExplain.txt
  json/ChipExplain_SupportExplain.txt
  json/Explain_Element_UserSkill.txt
  json/Explain_Element_UserSkill2.txt
  json/Illustrator.txt
  json/Name_Actor_Enemy.txt
  json/Name_Chip_AbilityEffectExplain.txt
  json/Name_Chip_ActiveName.txt
  json/Name_Chip_ExtraName.txt
  json/Name_Chip_SPArksName.txt
  json/Name_Chip_SupportName.txt
  json/Name_Quest_AreaName.txt
  json/Name_Quest_QuestName.txt
  json/UI_Text.txt
  json/UI_Weaponoid_Name.txt
  json/UI_Weaponoid_ReleaseAbility.txt
Labels: size/XXL

#121 Fix Salon Pass.
  json/Item_Stack_PaidPass.txt
Labels: size/XS
