Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-10, with the labels that each got.

#180 KO: fix typo
  json/Item_Stack_DeviceFD.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Weapon_AssaultRifle.txt
Labels: size/M

#181 Fix imports.
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Weapon_DualBlade.txt
Labels: size/XS

#182 Fix Seiga Summer Uniform Basewears.
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
Labels: size/S

#183 KO: Weapon name’s translation
  json/Item_LimitTimeQuestKey.txt
  json/Item_Stack_GatFMatFish.txt
  json/Item_Stack_GatFMatOther.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_Tact.txt
Labels: size/L

#147 EN: Consistent translation for 雅
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Name_UICharMake_AccessoryName.txt
  json/Name_UICharMake_BodyPartsName.txt
  json/Name_UICharMake_CostumeName.txt
  json/Name_UICharMake_HairStyleName.txt
Labels: size/XXL

#186 KO: fix typo and translation
  json/Item_BaseWear_Female.txt
  json/Item_InnerWear_Female.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Voice.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Katana.txt
Labels: size/XL

#187 Fix Merry Cannon description and Illustration-Style.
  json/Item_AvatarWPN_Launcher.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_ItemBag.txt
Labels: size/S

#188 KO: New scratch items
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Music.txt
Labels: size/L

#189 KO: fix typo and new translation
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/XL

#190 KO: fix typo and adding block names
  json/Block_All.txt
  json/Item_Stack_Enemy.txt
Labels: size/L

#191 KO: minor updates
  json/Explain_Actor_PA.txt
  json/Item_Costume_Male.txt
  json/Item_CraftItem.txt
  json/Item_Disk_PAAssaultRifle.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
  json/Item_Weapon_Partizan.txt
  json/Title_All.txt
Labels: size/L

#193 KO: additional translation
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/XL

#195 KO: Item's translation
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Tact.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/XL

#194 Fix Mags and rare enemy triggers.
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Enemy.txt
  json/Name_Actor_MagName.txt
Labels: size/S

#196 EN: Some things
  json/ChipExplain_SupportExplain.txt
  json/UI_Text.txt
Labels: size/S

#197 KO: fix typo
  json/Item_Costume_Female.txt
Labels: size/XS

#198 KO: fix typo
  json/Item_AvatarWPN_Sword.txt
  json/Item_BaseWear_Female.txt
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_ArmMale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_BodyMale.txt
  json/Item_Parts_LegFemale.txt
  json/Item_Parts_LegMale.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceAddTA.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Voice.txt
  json/Items_Leftovers.txt
Labels: size/L

#199 KO: fix typo
  json/Item_Stack_Music.txt
  json/Item_Weapon_DoubleSaber.txt
Labels: size/XS

#201 KO: units translation
  json/Item_Addon_Arm.txt
  json/Item_Addon_Back.txt
  json/Item_Addon_Unit.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Tact.txt
Labels: size/XL

#202 KO: fix typo
  json/Item_BaseWear_Female.txt
Labels: size/S

#204 KO: Leg items update
  json/Item_Addon_Arm.txt
  json/Item_Addon_Back.txt
  json/Item_Addon_Leg.txt
  json/Item_Weapon_Knuckle.txt
Labels: size/L

#205 Fix music discs and various titles.
  json/Item_Stack_Music.txt
  json/Title_All.txt
Labels: size/L

#206 Update Item_Stack_ItemBag.txt
  json/Item_Stack_ItemBag.txt
Labels: size/XS

#207 KO: fix typo
  json/Item_Stack_Tool.txt
Labels: size/XS

#208 KO: Weapon's translation
  json/Item_Addon_Arm.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
  json/Items_Leftovers.txt
Labels: size/XXL

#209 KO: Update new scratch items
  json/Item_Costume_Female.txt
  json/Item_Parts_ArmMale.txt
  json/Item_Parts_BodyMale.txt
  json/Item_Parts_LegMale.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_PaidTicket.txt
  json/Item_Weapon_TwinDagger.txt
Labels: size/XXL

#210 EN: Chip descriptions
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_SupportExplain.txt
Labels: size/L

#212 Fix Darkness Wing accessories, Dalmorts parts and Destiny music disc.
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_Music.txt
  json/Name_UICharMake_ArmPartsName.txt
  json/Name_UICharMake_BodyPartsName.txt
  json/Name_UICharMake_FaceVariationName.txt
  json/Name_UICharMake_LegPartsName.txt
Labels: size/M
