Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-09, with the labels that each got.

#142 EN: fix Alica to Alicia
  json/Item_Costume_Female.txt
Labels: size/XS

#143 EN: fix Eyde Rule to Adieloure
  json/Item_Costume_Female.txt
Labels: size/XS

#144 KO: Additional Translation
  json/Item_Costume_Female.txt
  json/Item_Disk_TECWind.txt
  json/Name_Actor_MagName.txt
Labels: size/S

#140 Fix Suit Jacket.
  json/Item_Outer_Male.txt
  json/Item_Stack_ItemBag.txt
  json/Name_UICharMake_CostumeName.txt
Labels: size/M

#145 KO: fix typo
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/M

#146 KO: fix minor typo
  json/Item_Outer_Female.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_GatOMatOther.txt
Labels: size/S

#149 KO: Weapon Translation
  json/Item_Weapon_GunSlash.txt
Labels: size/L

#150 KO: Fix typo
  json/Item_Stack_Tool.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/L

#151 KO: Revert to Japanese for awhile
  json/Item_Stack_Boost.txt
Labels: size/XL

#152 KO: Revert to Korean again
  json/Item_Stack_Boost.txt
Labels: size/XL

#154 KO: fix errors
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Pet_CandyCookie.txt
  json/Item_QuestTrigger.txt
Labels: size/M

#155 KO: Gunslash's translation
  json/Item_Outer_Male.txt
  json/Item_Weapon_GunSlash.txt
Labels: size/L

#156 Fix Modern Clock.
  json/Item_Stack_Roomgoods.txt
Labels: size/XS

#157 Fix Juno Charis Set.
  json/Item_Stack_ItemBag.txt
Labels: size/XS

#158 Fix remaining GUARDIANS costumes.
  json/Item_Costume_Female.txt
Labels: size/S

#159 KO: Order item's translation
  json/Item_Stack_Orderitem.txt
Labels: size/M

#160 Fix Silva's hair and rifle.
  json/Item_Stack_Hairstyle.txt
  json/Item_Weapon_AssaultRifle.txt
Labels: size/XS

#161 KO: fix typo and translation
  json/Item_Stack_Boost.txt
  json/Item_Stack_Orderitem.txt
Labels: size/L

#162 Fix Sakuya Mode-C Repca name consistency.
  json/Item_Costume_Female.txt
Labels: size/S

#163 KO: Boost Items translation
  json/Item_QuestTrigger.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_Tool.txt
Labels: size/L

#164 EN: New item stuff
  json/Item_AvatarWPN_Katana.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_ArmMale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_BodyMale.txt
  json/Item_Parts_LegFemale.txt
  json/Item_Parts_LegMale.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_PaidPass.txt
Labels: size/L

#167 Various fixes
  json/Explain_Element_Special.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Tool.txt
Labels: size/M

#168 Fix typo in Reinier Nova.
  json/Item_Weapon_WiredLance.txt
Labels: size/XS

#166 KO: Additional Translation
  json/Item_Addon_Arm.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_Heal.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Title_All.txt
Labels: size/XL

#169 KO: fix errors
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_QuestTrigger.txt
  json/Item_RingR.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatOther.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Title_All.txt
Labels: size/L

#170 KO: fix errors
  json/Item_Stack_GatOMatOther.txt
  json/Item_Stack_Heal.txt
Labels: size/XS

#172 KO: Additional Translation
  json/Item_Costume_Male.txt
  json/Item_Stack_GatCMatCereal.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/XXL

#173 KO: fix typo
  json/Item_AvatarWPN_Katana.txt
  json/Item_Stack_Accessory.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Talis.txt
Labels: size/XL

#174 Various fixes.
  json/Name_Actor_MagName.txt
  json/Title_All.txt
Labels: size/XS

#175 Fix typo in spicy parfaits.
  json/Item_Pet_CandyParfait.txt
Labels: size/S

#176 KO: fix typo
  json/Item_Costume_Female.txt
  json/Item_Weapon_AssaultRifle.txt
Labels: size/S

#177 RU: Block upd
  json/Block_All.txt
Labels: size/M

#178 KO: Additional Translation
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Voice.txt
Labels: size/L

#179 KO: fix typo
  json/Item_Stack_Accessory.txt
Labels: size/XS
