Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-03, with the labels that each got.

#6 EN: Fix weird line breaks
  json/Title_All.txt
Labels: size/XL

#10 Update items
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_ArmMale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_BodyMale.txt
  json/Item_Parts_LegFemale.txt
  json/Item_Parts_LegMale.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_Voice.txt
Labels: size/XL

#11 Fix spelling
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_ItemBag.txt
Labels: size/S

#8 [RU] Update: Title_All + a bit ui_text for check
  json/Title_All.txt
  json/UI_Text.txt
Labels: size/XL

#13 EN: Knuckle/Battle Arena/1-6* weapon camo descriptions
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_Compoundbow.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_GunSlash.txt
  json/Item_AvatarWPN_JetBoots.txt
  json/Item_AvatarWPN_Katana.txt
  json/Item_AvatarWPN_Knuckle.txt
  json/Item_AvatarWPN_Launcher.txt
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_Tact.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_AvatarWPN_TwinMachineGun.txt
  json/Item_AvatarWPN_Wand.txt
  json/Item_AvatarWPN_WiredLance.txt
Labels: size/L

#17 Gunslash camos + some fixes
  json/Item_AvatarWPN_GunSlash.txt
  json/Item_AvatarWPN_JetBoots.txt
  json/Item_AvatarWPN_Wand.txt
Labels: size/M

#18 EN: Wand camos and some others
  json/Item_AvatarWPN_GunSlash.txt
  json/Item_AvatarWPN_JetBoots.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_Wand.txt
Labels: size/M

#19 ES: Titles Update
  json/Title_All.txt
Labels: size/L

#21 EN: Various fixes
  json/Item_AvatarWPN_Sword.txt
  json/Item_QuestTrigger.txt
  json/Item_Weapon_TwinDagger.txt
  json/Title_All.txt
Labels: size/M

#22 EN: Fix up titles with no IDs
  json/Title_All.txt
Labels: size/L

#29 EN: Last few fixes
  json/Title_All.txt
Labels: size/S

#30 [RU] Fix titles
  json/Title_All.txt
Labels: size/XS

#31 Fixes to descriptions
  json/Title_All.txt
Labels: size/M

#32 EN: NPC partner titles + couple others
  json/Title_All.txt
Labels: size/L

#33 EN: Fix clipping
  json/Title_All.txt
Labels: size/M

#34 EN: Remove dups, fix leading spaces
  json/Title_All.txt
Labels: size/M

#35 ES: Update
  json/Title_All.txt
Labels: size/L

#36 RU: Update
  json/Title_All.txt
Labels: size/L

#37 EN: Mostly grind titles
  json/Item_Stack_Music.txt
  json/Item_Stack_Roomgoods.txt
  json/Title_All.txt
Labels: size/L

#40 ES: Updates
  json/Item_AvatarWPN_Launcher.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
  json/Item_Weapon_GunSlash.txt
  json/Name_Actor_Enemy.txt
  json/Title_All.txt
Labels: size/XL

#41 RU: Updates
  json/Item_AvatarWPN_Launcher.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
  json/Item_Weapon_GunSlash.txt
  json/Name_Actor_Enemy.txt
  json/Title_All.txt
Labels: size/XL

#39 EN: Titles and updates
  json/Item_AvatarWPN_Launcher.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
  json/Title_All.txt
Labels: size/M

#42 EN: Last two endless quest title descriptions
  json/Title_All.txt
Labels: size/XS

#43 EN: Possible crash fix
  json/Item_Stack_Roomgoods.txt
Labels: size/XS

#44 EN: Updates and fixes
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_GunSlash.txt
  json/Item_BaseWear_Female.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_ArmMale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_BodyMale.txt
  json/Item_Parts_LegFemale.txt
  json/Item_Parts_LegMale.txt
  json/Item_Pet_CandyParfait.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceFD.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_DualBlade.txt
  json/Season3_Text.txt
Labels: size/XL

#45 EN: Items
  _tools/TicketDescriptions.py
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_GunSlash.txt
  json/Item_AvatarWPN_JetBoots.txt
  json/Item_AvatarWPN_Katana.txt
  json/Item_AvatarWPN_Knuckle.txt
  json/Item_AvatarWPN_Launcher.txt
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_AvatarWPN_TwinMachineGun.txt
  json/Item_AvatarWPN_Wand.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_Disk_PAKatana.txt
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_ArmMale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_BodyMale.txt
  json/Item_Parts_LegFemale.txt
  json/Item_Parts_LegMale.txt
  json/Item_Pet_CandyCookie.txt
  json/Item_Pet_CandyGumi.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Voice.txt
Labels: size/L

#47 EN: Tiny fixes
  json/Explain_Actor_PA.txt
  json/Item_Disk_PAKatana.txt
  json/Item_Stack_LobbyAction.txt
Labels: size/XS

#48 EN: Try title fix
  json/Title_All.txt
Labels: size/XS

#49 ES: Title Update 26-03-2020
  json/Title_All.txt
Labels: size/XL

#52 EN: IDs, names, gaidens, simple descriptions
  ChipAndAbilityIDs.txt
  _tools/GaidenEffects.py
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_BoostSkillExplain.txt
  json/ChipExplain_SupportExplain.txt
  json/Name_Chip_ActiveName.txt
  json/Name_Chip_SupportName.txt
  json/TowerQuest_BlockNameText.txt
  json/TowerQuest_TowerNameText.txt
  json/UI_Weaponoid_BondsEffect.txt
  json/UI_Weaponoid_Name.txt
  json/UI_Weaponoid_ReleaseAbility.txt
Labels: size/XL
