Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-06, with the labels that each got.

#85 Fix regular Magatsu titles
  json/Title_All.txt
Labels: size/XS

#86 Fix Gwanah Daggers name in titles
  json/Title_All.txt
Labels: size/XS

#87 EN: Outerwear and costumes
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_LegFemale.txt
Labels: size/XL

#90 EN: New chip descriptions
  ChipAndAbilityIDs.txt
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_SupportExplain.txt
  json/Name_Chip_ExtraName.txt
  json/Name_Chip_SPArksName.txt
  json/Name_Chip_SupportName.txt
Labels: size/L

#89 EN: Jet Boots item description translation.
  json/Item_Weapon_JetBoots.txt
Labels: size/M

#91 Fix music disc description errors.
  json/Item_Stack_Music.txt
Labels: size/S

#92 Fix Ichika's title name
  json/Title_All.txt
Labels: size/XS

#93 EN: Redo missing UI translations
  json/ChipExplain_SupportExplain.txt
  json/UI_Text.txt
Labels: size/L

#94 Fix Power Generating Lillipan
  json/Item_Stack_Accessory.txt
Labels: size/XS

#95 EN: fix build issues
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceFD.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_PaidPass.txt
Labels: size/M

#96 EN: remove double spaces
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_Roomgoods.txt
  json/Name_UICharMake_LegPartsName.txt
  json/UI_QuestTips.txt
Labels: size/XS

#97 EN: New items and Hitogata numbers
  json/ChipExplain_SupportExplain.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceFD.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
Labels: size/L

#99 Fix names and descriptions.
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Name_UICharMake_ArmPartsName.txt
  json/Name_UICharMake_CostumeName.txt
  json/Name_UICharMake_HairStyleName.txt
  json/Name_UICharMake_LegPartsName.txt
Labels: size/S

#98 EN: Making a start on male costume descriptions
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinMachineGun.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
Labels: size/XL

#100 EN: Finish costumes with both sex variants
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
Labels: size/XL

#102 Kaerun mag for rainy day.
  json/Item_Stack_DeviceHT.txt
Labels: size/XS

#101 EN: Even more male costumes
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Stack_ItemBag.txt
Labels: size/L
