Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-11, with the labels that each got.

#214 Fix for SG Recycle Badge, S.CN Arbor Stag, FOmarl costumes.
  json/Item_Costume_Female.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_TwinDagger.txt
Labels: size/XS

#216 KO: New weapon's translation
  json/Item_AvatarWPN_Wand.txt
  json/Item_Stack_Accessory.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Tact.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/L

#217 EN: Update from es DBs
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_ItemBag.txt
  json/Name_UICharMake_CostumeName.txt
  json/SeraphyRoom_SeraphyNote.txt
Labels: size/M

#218 KO: update minor translation
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_Wand.txt
Labels: size/XS

#219 KO: item's translation
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Wand.txt
Labels: size/XS

#220 KO: item's translation
  json/Item_AvatarWPN_Sword.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
Labels: size/L

#221 KO: update items
  json/Item_BaseWear_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_QuestTrigger.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/L

#222 KO: fix typo
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Male.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatJewel.txt
  json/Item_Stack_Orderitem.txt
Labels: size/L

#223 EN: Today's update
  json/Arles_Text.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_Tact.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_AvatarWPN_Wand.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Weapon_GunSlash.txt
Labels: size/M
