Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-12, with the labels that each got.

#224 KO: update items
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_Tact.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_AvatarWPN_Wand.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Weapon_GunSlash.txt
Labels: size/L

#225 KO: fix typo
  json/Item_Stack_PaidPass.txt
Labels: size/XS

#226 Latest changes
  json/Awakening_Skill_Explain_Token.txt
Labels: size/XS

#227 KO: additional translation
  json/Item_Stack_PaidPass.txt
Labels: size/M

#228 KO: fix typo
  json/Item_Stack_Tool.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/XS

#229 KO : add title
  json/Item_Weapon_Sword.txt
  json/Title_All.txt
Labels: size/XS

#230 Update Item_Costume_Male.txt
  json/Item_Costume_Male.txt
Labels: size/S

#231 KO: fix typo
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_GatBoost.txt
  json/Item_Stack_GatFMatFish.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_PaidPass.txt
Labels: size/S

#232 KO: fix typo
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Pet_Egg.txt
  json/Item_QuestTrigger.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
Labels: size/XXL

#234 EN: Some update stuff
  _py/coverage.py
  json/Explain_Element_Booster.txt
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_GunSlash.txt
  json/Item_AvatarWPN_Katana.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_AvatarWPN_Wand.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_QuestTrigger.txt
  json/Name_Chip_ActiveName.txt
  json/Name_Chip_SPArksName.txt
  json/Name_Chip_SupportName.txt
  json/UI_Weaponoid_BallonName.txt
  json/UI_Weaponoid_Name.txt
Labels: size/L

#235 KO: fix typo
  json/Item_Costume_Male.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/S
