Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2020-04, with the labels that each got.

#55 EN: Some fixes
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_SupportExplain.txt
  json/UI_Text.txt
Labels: size/M

#56 [RU] Block mini fix
  json/Block_All.txt
Labels: size/S

#57 EN: The update
  json/Awakening_Skill_Explain_Token.txt
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_SupportExplain.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Name_Chip_SPArksName.txt
  json/Name_Quest_AreaName.txt
  json/Name_Quest_QuestName.txt
  json/UI_Text.txt
Labels: size/XL

#58 ES: Update
  json/Awakening_Skill_Explain_Token.txt
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_SupportExplain.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Weapon_WiredLance.txt
  json/Name_Chip_SPArksName.txt
  json/Name_Quest_AreaName.txt
  json/Name_Quest_QuestName.txt
  json/UI_Text.txt
Labels: size/XXL

#63 EN: Some items
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Sticker.txt
Labels: size/M

#65 RU: Update
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Sticker.txt
  json/Title_All.txt
Labels: size/L

#64 ES: Update
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Sticker.txt
  json/Title_All.txt
Labels: size/L

#66 EN: Sakura Wars chips + some numbers
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_SupportExplain.txt
Labels: size/S

#67 EN: Some camo descriptions
  json/Item_AvatarWPN_Talis.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/S

#68 EN: Couple of minor things
  json/ChipExplain_SupportExplain.txt
  json/Name_Chip_LiquidationMaterialName.txt
  json/Name_Chip_SupportName.txt
Labels: size/S

#69 EN: Fixes
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Katana.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Roomgoods.txt
Labels: size/M

#71 EN: update TDVR titles
  json/Title_All.txt
Labels: size/S

#72 EN: Scratch items
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Name_Actor_MagName.txt
Labels: size/L

#77 EN: 29 April update
  json/ChipExplain_SupportExplain.txt
Labels: size/XS

#75 ES: Update
  json/ChipExplain_SupportExplain.txt
Labels: size/XS

#78 RU: Update
  json/ChipExplain_SupportExplain.txt
Labels: size/XS
