Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2021-07, with the labels that each got.

#300 KO: update SG items
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_NGS_Mouth.txt
  json/Item_NGS_Stamps.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Tool.txt
  json/Item_Stack_Voice.txt
  json/Item_Weapon_GunSlash.txt
  json/Name_UICharMake_HairStyleName.txt
Labels: size/L

#301 KO: Fix typo
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_Stack_GatFMatShellfish.txt
Labels: size/XS

#306 Update premium tickets.
  json/Item_Stack_PaidTicket.txt
Labels: size/S
