Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2021-08, with the labels that each got.

#307 KO: Update challenge quest skill items
  json/Items_Leftovers.txt
Labels: size/L

#308 KO: fix items
  json/Explain_SkillRing.txt
  json/Items_Leftovers.txt
Labels: size/S

#305 PSO2es EN: Various fixes.
  json/Explain_Actor_MagAuto.txt
  json/Explain_Actor_MagTrigger.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Costume_Female.txt
  json/Item_CraftItem.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Mouth.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_PaidTicket.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
  json/Items_Leftovers.txt
  json/Name_Chip_SPArksName.txt
  json/Name_UICharMake_CostumeName.txt
  json/Name_UICharMake_HairStyleName.txt
  json/Title_All.txt
  json/UI_Text.txt
Labels: size/XXL

#309 Fix materials.
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
Labels: size/S

#311 KO: Update Item_Stack_EyeLash.txt
  json/Item_Stack_EyeLash.txt
Labels: size/XS

#312 Update Items_Leftovers.txt
  json/Items_Leftovers.txt
Labels: size/XS

#313 PSO2es EN: Various Fixes
  json/Condition_Group.txt
  json/Illustrator.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Name_Chip_AbilityEffectExplain.txt
  json/Name_Chip_DarkerName.txt
  json/Name_Chip_SPArksName.txt
  json/Name_Quest_AreaName.txt
  json/TowerQuest_TowerNameText.txt
  json/UI_Text.txt
  json/UI_Weaponoid_BallonName.txt
  json/UI_Weaponoid_Name.txt
Labels: size/L

#314 PSO2es EN: Import translations.
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Mouth.txt
  json/Item_NGS_Stamps.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
Labels: size/L

#315 PSO2es EN 25th Aug
  json/Item_AvatarWPN_Partizan.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Stamps.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Name_Chip_SupportName.txt
  json/Season1_Text.txt
  json/UI_Text.txt
Labels: size/XL

#318 PSO2es EN: Minor fixes
  json/Item_Stack_DeviceHT.txt
  json/Name_Actor_MagName.txt
  json/Name_UICharMake_CostumeName.txt
Labels: size/S
