Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2021-04, with the labels that each got.

#259 Translate exclusives and various fixes.
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_PaidTicket.txt
Labels: size/L

#260 Ru: TicketDescriptions.py
  _tools/TicketDescriptions.py
Labels: size/L

#262 Ru: long title name fix + 1 part end
  json/Item_Stack_Headparts.txt
  json/Item_Stack_Heal.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Title_All.txt
  json/UI_Server.txt
Labels: size/L

#263 Translate limited time fun shop items.
  json/Item_Stack_Roomgoods.txt
Labels: size/S

#267 Mag trigger action fixes and stuff
  json/Explain_Actor_MagTrigger.txt
  json/Items_Leftovers.txt
  json/UI_Text.txt
Labels: size/S

#269 Fix lobby action name
  json/Item_Stack_LobbyAction.txt
Labels: size/XS

#268 Fix psnova weapon name
  json/Item_AvatarWPN_Partizan.txt
Labels: size/XS

#270 Manually import translations and fix some text.
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/UI_Text.txt
Labels: size/M

#271 Skiing Lillipan
  json/Item_Stack_Accessory.txt
Labels: size/XS
