Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2021-01, with the labels that each got.

#236 KO: translating weapon camo
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_Outer_Female.txt
Labels: size/L

#237 KO: Additional Work
  json/Explain_Actor_PA.txt
  json/Item_BaseWear_Female.txt
  json/Item_Disk_PACompoundbow.txt
  json/Item_Disk_PACustAssaultRifle.txt
  json/Item_Disk_PACustCompoundbow.txt
  json/Item_Disk_PACustDoubleSaber.txt
  json/Item_Disk_PACustDualBlade.txt
  json/Item_Disk_PACustGunSlash.txt
  json/Item_Disk_PACustJetBoots.txt
  json/Item_Disk_PACustKatana.txt
  json/Item_Disk_PACustKnuckle.txt
  json/Item_Disk_PACustLauncher.txt
  json/Item_Disk_PACustPartizan.txt
  json/Item_Disk_PACustSword.txt
  json/Item_Disk_PACustTwinDagger.txt
  json/Item_Disk_PACustTwinMachineGun.txt
  json/Item_Disk_PACustWiredLance.txt
  json/Item_Disk_PADoubleSaber.txt
  json/Item_Disk_PADualBlade.txt
  json/Item_Disk_PAGunSlash.txt
  json/Item_Disk_PAJetBoots.txt
  json/Item_Disk_PAKatana.txt
  json/Item_Disk_PAKnuckle.txt
  json/Item_Disk_PALauncher.txt
  json/Item_Disk_PAPartizan.txt
  json/Item_Disk_PASword.txt
  json/Item_Disk_PATwinDagger.txt
  json/Item_Disk_PATwinMachineGun.txt
  json/Item_Disk_PAWiredLance.txt
  json/Item_Disk_TECCustDark.txt
  json/Item_Disk_TECCustFire.txt
  json/Item_Disk_TECCustIce.txt
  json/Item_Disk_TECCustLight.txt
  json/Item_Disk_TECCustThunder.txt
  json/Item_Disk_TECCustWind.txt
  json/Item_Disk_TECDark.txt
  json/Item_Disk_TECFire.txt
  json/Item_Disk_TECIce.txt
  json/Item_Disk_TECLight.txt
  json/Item_Disk_TECMultiple.txt
  json/Item_Disk_TECThunder.txt
  json/Item_Disk_TECWind.txt
  json/Item_Outer_Female.txt
Labels: size/XL

#238 KO: additional translation
  json/Item_QuestTrigger.txt
  json/Item_Stack_Orderitem.txt
Labels: size/M

#240 EN: Ticket description translator refactor and results
  _tools/TicketDescriptions.py
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
Labels: size/L
