Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2021-06, with the labels that each got.

#286 KO: focuslite is idiot. he's forgot to make PR
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinMachineGun.txt
  json/Item_AvatarWPN_WiredLance.txt
Labels: size/L

#288 KO: fix typo
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Tool.txt
Labels: size/XS

#289 KO: Fix typo
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
Labels: size/S

#290 KO: fix typo
  json/Item_Stack_GatCMatMineral.txt
Labels: size/XS

#292 RU: NGS items
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Stamps.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_Tool.txt
Labels: size/L

#294 Ru: Returning translation + some new
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Motion.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_PaidTicket.txt
Labels: size/L

#293 Tools: powershell script to copy PSO2es items to PSO2
  _tools/export-salon.ps1
Labels: size/L

#284 Various fixes
  json/Explain_Element_Booster.txt
  json/Explain_SkillRing.txt
  json/Item_RingL.txt
  json/Item_Stack_DeviceTA.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
  json/Items_Leftovers.txt
  json/UI_Text.txt
Labels: size/XL

#295 Fix Sarisa stamp.
  json/Item_NGS_Stamps.txt
Labels: size/XS

#296 PSO2es EN: Various fixes
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_HandPose.txt
  json/Item_NGS_Motion.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/M

#297 Fix block names.
  json/Block_All.txt
Labels: size/XS

#298 Fix Ares Machineguns.
  json/Item_Weapon_TwinMachineGun.txt
Labels: size/XS
