Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2021-05, with the labels that each got.

#274 Fix Wilke cast set
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_LegFemale.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_ItemBag.txt
  json/Name_UICharMake_ArmPartsName.txt
  json/Name_UICharMake_BodyPartsName.txt
  json/Name_UICharMake_HairStyleName.txt
  json/Name_UICharMake_LegPartsName.txt
Labels: size/M

#276 Extreme Survival stuff now that it's actually happening
  json/UI_Text.txt
Labels: size/M

#277 Various fixes
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_Roomgoods.txt
  json/Name_Quest_QuestName.txt
  json/Name_UICharMake_ArmPartsName.txt
  json/Name_UICharMake_BodyPartsName.txt
  json/Name_UICharMake_CostumeName.txt
  json/Name_UICharMake_HairStyleName.txt
  json/Name_UICharMake_LegPartsName.txt
  json/UI_Text.txt
Labels: size/L

#278 Translate items and fix enemy item name
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_Outer_Female.txt
  json/Item_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceLevel.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_PaidTicket.txt
  json/Title_All.txt
Labels: size/L

#282 [RU] just fix
  json/Item_Pet_CandyParfait.txt
  json/Item_Stack_Orderitem.txt
Labels: size/S

#283 KO: sword camos
  json/Item_AvatarWPN_Sword.txt
Labels: size/L

#285 Fix name references
  json/ChipExplain_SupportExplain.txt
  json/Explain_SkillRing.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_FacePattern.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_GatOMatOther.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_Tool.txt
  json/Name_Actor_MagName.txt
  json/Name_Chip_SPArksName.txt
  json/Name_Quest_AreaName.txt
  json/Name_Quest_QuestName.txt
  json/SeraphyRoom_SeraphyNote.txt
  json/Title_All.txt
  json/UI_QuestTips.txt
  json/UI_Text.txt
  json/UI_Weaponoid_BallonName.txt
  json/UI_Weaponoid_Name.txt
Labels: size/L
