Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2022-04, with the labels that each got.

#355 CN: Update translations of update 0406
  _tools/TicketDescriptions.py
  json/Item_Addon_Unit.txt
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Motion.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/XXL

#356 CN: add translation of classic boost item
  json/Item_FacePattern.txt
  json/Item_InnerWear_Female.txt
  json/Item_NGS_Ear.txt
  json/Item_NGS_Horn.txt
  json/Item_NGS_Mouth.txt
  json/Item_NGS_Outer_Female.txt
  json/Item_NGS_Outer_Male.txt
  json/Item_NGS_Parts_Male.txt
  json/Item_NGS_Stamps.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_LobbyAction.txt
Labels: size/XXL

#358 CN: remove EN translation in acc, remove CN traslation in some items
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_NGS_Motion.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Tool.txt
Labels: size/XL

#359 CN: remove missed translation can be sold
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_NGS_Motion.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/XXL

#361 CN: fix desc too long.
  json/Item_NGS_Motion.txt
  json/Item_Stack_DeviceCL.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Tool.txt
Labels: size/L

#363 CN: fix TickerDesc script, and run it.
  _tools/TicketDescriptions.py
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Outer_Female.txt
  json/Item_NGS_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_PaidTicket.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Tool.txt
  json/Item_Stack_Voice.txt
Labels: size/XXL

#364 CN: Update
  _tools/TicketDescriptions.py
  json/Item_NGS_Ear.txt
  json/Item_NGS_Horn.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Mouth.txt
  json/Item_NGS_Outer_Female.txt
  json/Item_NGS_Outer_Male.txt
  json/Item_NGS_Parts_Female.txt
  json/Item_NGS_Parts_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
Labels: size/XXL

#365 CN: Remove new items' EN and add location & monster to material's desc
  json/Item_NGS_Ear.txt
  json/Item_NGS_Parts_Female.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
Labels: size/L

#366 CN: fix circleci error, font_big.
  _tools/TicketDescriptions.py
  json/Item_Stack_LobbyAction.txt
Labels: size/XL

#367 CN: try to fix LA font_big error
  _tools/TicketDescriptions.py
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_LobbyAction.txt
Labels: size/XXL

#368 CN: Improve translation quality
  _tools/TicketDescriptions.py
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Outer_Female.txt
  json/Item_NGS_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Tool.txt
  json/Item_Stack_Voice.txt
Labels: size/XXL

#369 RU: New item + some EN item reset
  json/Item_FacePattern.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Ear.txt
  json/Item_NGS_Horn.txt
  json/Item_NGS_Mouth.txt
  json/Item_NGS_Stamps.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Tool.txt
Labels: size/XXL

#370 CN: Update new capsuleabilities
  _tools/TicketDescriptions.py
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Outer_Female.txt
  json/Item_NGS_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_DeviceCL.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Tool.txt
Labels: size/XXL

#372 CN: Add pa and skill disk desc translation for CH quests
  json/Item_Disk_PAAssaultRifle.txt
  json/Item_Disk_PACompoundbow.txt
  json/Item_Disk_PADoubleSaber.txt
  json/Item_Disk_PADualBlade.txt
  json/Item_Disk_PAGunSlash.txt
  json/Item_Disk_PAJetBoots.txt
  json/Item_Disk_PAKatana.txt
  json/Item_Disk_PAKnuckle.txt
  json/Item_Disk_PALauncher.txt
  json/Item_Disk_PAPartizan.txt
  json/Item_Disk_PASword.txt
  json/Item_Disk_PATwinDagger.txt
  json/Item_Disk_PATwinMachineGun.txt
  json/Item_Disk_PAWiredLance.txt
  json/Item_Disk_TECDark.txt
  json/Item_Disk_TECFire.txt
  json/Item_Disk_TECIce.txt
  json/Item_Disk_TECLight.txt
  json/Item_Disk_TECMultiple.txt
  json/Item_Disk_TECThunder.txt
  json/Item_Disk_TECWind.txt
  json/Items_Leftovers.txt
Labels: size/XL

#373 CN: Fix too long error for PA and skill disk
  json/Item_Disk_PAAssaultRifle.txt
  json/Item_Disk_PADoubleSaber.txt
  json/Item_Disk_PAGunSlash.txt
  json/Item_Disk_PAKnuckle.txt
  json/Item_Disk_PALauncher.txt
  json/Item_Disk_PATwinMachineGun.txt
  json/Item_Disk_PAWiredLance.txt
  json/Item_Disk_TECDark.txt
  json/Item_Disk_TECWind.txt
  json/Items_Leftovers.txt
Labels: size/L

#374 CN: Fix too long error for PA and skill disk translation
  json/Item_Disk_PAAssaultRifle.txt
  json/Item_Disk_PATwinMachineGun.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Items_Leftovers.txt
Labels: size/S

#375 CN: Fix too long error for meat desc translation
  json/Item_Stack_GatOMatMeat.txt
Labels: size/XS

#376 CN: PA/TEC discs: hightlight the item name in description; fix the too long strings; fix some translation
  json/Item_Disk_PAAssaultRifle.txt
  json/Item_Disk_PACompoundbow.txt
  json/Item_Disk_PADoubleSaber.txt
  json/Item_Disk_PADualBlade.txt
  json/Item_Disk_PAGunSlash.txt
  json/Item_Disk_PAJetBoots.txt
  json/Item_Disk_PAKatana.txt
  json/Item_Disk_PAKnuckle.txt
  json/Item_Disk_PALauncher.txt
  json/Item_Disk_PAPartizan.txt
  json/Item_Disk_PASword.txt
  json/Item_Disk_PATwinDagger.txt
  json/Item_Disk_PATwinMachineGun.txt
  json/Item_Disk_PAWiredLance.txt
  json/Item_Disk_TECDark.txt
  json/Item_Disk_TECFire.txt
  json/Item_Disk_TECIce.txt
  json/Item_Disk_TECLight.txt
  json/Item_Disk_TECMultiple.txt
  json/Item_Disk_TECThunder.txt
  json/Item_Disk_TECWind.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Items_Leftovers.txt
Labels: size/L

#371 CN: Update
  json/ChipExplain_ActiveExplain.txt
  json/Item_Stack_Sticker.txt
  json/SeraphyRoom_SeraphyNote.txt
  json/UI_Text.txt
Labels: size/M

#377 CN: fix the too long strings
  json/Item_Disk_PAAssaultRifle.txt
  json/Item_Disk_PAKnuckle.txt
  json/Item_Disk_TECWind.txt
  json/Item_Stack_GatOMatMeat.txt
Labels: size/XS

#378 CN: Add tr_text for those explains have been translated.
  json/Item_Disk_PAAssaultRifle.txt
  json/Item_Disk_PACompoundbow.txt
  json/Item_Disk_PADoubleSaber.txt
  json/Item_Disk_PADualBlade.txt
  json/Item_Disk_PAGunSlash.txt
  json/Item_Disk_PAJetBoots.txt
  json/Item_Disk_PAKatana.txt
  json/Item_Disk_PAKnuckle.txt
  json/Item_Disk_PALauncher.txt
  json/Item_Disk_PAPartizan.txt
  json/Item_Disk_PASword.txt
  json/Item_Disk_PATwinDagger.txt
  json/Item_Disk_PATwinMachineGun.txt
  json/Item_Disk_PAWiredLance.txt
  json/Item_Disk_TECDark.txt
  json/Item_Disk_TECFire.txt
  json/Item_Disk_TECIce.txt
  json/Item_Disk_TECLight.txt
  json/Item_Disk_TECMultiple.txt
  json/Item_Disk_TECThunder.txt
  json/Item_Disk_TECWind.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Outer_Female.txt
  json/Item_NGS_Outer_Male.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
Labels: size/XXL

#380 CN: Add new translation (PSO2 mag devices etc.)
  json/Explain_System.txt
  json/Item_LimitTimeQuestKey.txt
  json/Item_Stack_DeviceAA.txt
  json/Item_Stack_DeviceAddTA.txt
  json/Item_Stack_DeviceFD.txt
  json/Item_Stack_DeviceLevel.txt
  json/Item_Stack_DevicePB.txt
  json/Item_Stack_DeviceSAA.txt
  json/Item_Stack_DeviceTA.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_Orderitem.txt
  json/Name_Actor_MagName.txt
Labels: size/L

#381 CN: add critical field disk for CH
  json/Items_Leftovers.txt
Labels: size/XS

#382 CN: Fix <br> with \n
  json/Item_Stack_DeviceTA.txt
Labels: size/M

#383 CN: Fix <br> with \n
  json/Item_Stack_DeviceTA.txt
Labels: size/M
