Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2022-01, with the labels that each got.

#334 Fibra -> Fivra
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Wand.txt
Labels: size/S

#339 KO: Update items
  json/Item_BaseWear_Female.txt
  json/Item_Costume_Female.txt
  json/Item_Costume_Male.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_PaidTicket.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/XXL

#340 KO: Update items
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/L

#341 KO: Update Item_Stack_Tool.txt
  json/Item_Stack_Tool.txt
Labels: size/S

#342 KO: fix error
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Weapon_DoubleSaber.txt
Labels: size/L

#344 KO: Update items to release
  json/Item_Addon_Unit.txt
  json/Item_NGS_CapsuleAbilities.txt
Labels: size/L

#345 KO:Fix typo
  json/Item_NGS_CapsuleAbilities.txt
Labels: size/XS

#346 KO: Update missing caps
  json/Item_NGS_CapsuleAbilities.txt
Labels: size/L

#347 KO: update items
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_Stack_GatCMatVegetable.txt
Labels: size/S

#348 Foursis
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/S
