Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2022-07, with the labels that each got.

#393 CN: Add guide description for Kvaris meat
  json/Item_Addon_Unit.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
Labels: size/M

#394 CN: minor fixes
  json/Item_Stack_Music.txt
Labels: size/XS

#395 CN: fix missing ',' delimiter
  json/Item_Weapon_Compoundbow.txt
Labels: size/XS

#396 Scratch Select Tickets
  json/Item_Stack_GachaTradePass.txt
Labels: size/L

#397 descriptions
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Katana.txt
  json/Item_AvatarWPN_Knuckle.txt
  json/Item_AvatarWPN_Launcher.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_AvatarWPN_TwinMachineGun.txt
  json/Item_AvatarWPN_Wand.txt
  json/Item_Stack_Tool.txt
Labels: size/L

#398 additional fixes
  json/Explain_Actor_MagPhotonBlast.txt
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_JetBoots.txt
  json/Item_AvatarWPN_Katana.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_Disk_PAJetBoots.txt
  json/Item_Disk_PALauncher.txt
  json/Item_Disk_PASword.txt
  json/Item_Stack_DevicePB.txt
  json/Item_Stack_GatOMatOther.txt
  json/Item_Stack_Orderitem.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Tool.txt
  json/Season1_Text.txt
  json/Season2_Text.txt
  json/UI_Text.txt
Labels: size/L

#400 tickets, consumables, miscellaneous
  json/Item_AvatarWPN_Sword.txt
  json/Item_NGS_Motion.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_Voice.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/L

#401 Ticket Description Fix
  json/Item_Stack_GachaTradePass.txt
Labels: size/M

#399 CN: minor fixes; update augments list according to the item_element_reb
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Tool.txt
Labels: size/XXL
