Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2022-06, with the labels that each got.

#384 CN: Add new translation (Skill rings & NGS armor), update the skill d…
  json/Item_Addon_Unit.txt
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_AvatarWPN_WiredLance.txt
  json/Item_Disk_TECCustDark.txt
  json/Item_Disk_TECCustFire.txt
  json/Item_Disk_TECCustIce.txt
  json/Item_Disk_TECCustLight.txt
  json/Item_Disk_TECCustThunder.txt
  json/Item_Disk_TECCustWind.txt
  json/Item_Disk_TECDark.txt
  json/Item_Disk_TECFire.txt
  json/Item_Disk_TECIce.txt
  json/Item_Disk_TECLight.txt
  json/Item_Disk_TECThunder.txt
  json/Item_Disk_TECWind.txt
  json/Item_RingL.txt
  json/Item_RingR.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_DeviceCL.txt
  json/Item_Stack_DevicePB.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
  json/Items_Leftovers.txt
Labels: size/XXL

#386 CN: fix a typo error
  json/Item_RingR.txt
Labels: size/XS

#387 Ru: New content
  json/Item_NGS_Ear.txt
  json/Item_NGS_Horn.txt
  json/Item_NGS_Mouth.txt
  json/Item_Parts_ArmFemale.txt
  json/Item_Parts_ArmMale.txt
  json/Item_Parts_BodyFemale.txt
  json/Item_Parts_BodyMale.txt
  json/Item_Parts_LegFemale.txt
  json/Item_Parts_LegMale.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_PaidTicket.txt
  json/Item_Stack_Tool.txt
  json/Item_Stack_Voice.txt
  json/UI_Text.txt
Labels: size/XXL

#388 CN: delete EN translation for update 20220608
  json/Item_Addon_Unit.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_NGS_Ear.txt
  json/Item_NGS_Horn.txt
  json/Item_NGS_Mouth.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/XXL

#389 CN: Item translations for update 20220608
  json/Item_Addon_Unit.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Katana.txt
  json/Item_AvatarWPN_Launcher.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinMachineGun.txt
  json/Item_AvatarWPN_Wand.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_RingL.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_GatCMatFruit.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatShellfish.txt
  json/Item_Stack_GatOMatMeat.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_PaidTicket.txt
  json/Item_Stack_Tool.txt
Labels: size/XL

#390 CN: Delete 2 missing EN translation for LobbyAction
  json/Item_Stack_LobbyAction.txt
Labels: size/XS

#391 CN: Armors translation; minor fixes
  json/Item_Addon_Unit.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_Tool.txt
  json/Item_Weapon_AssaultRifle.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_DualBlade.txt
  json/Item_Weapon_JetBoots.txt
  json/Item_Weapon_Katana.txt
  json/Item_Weapon_Knuckle.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Rod.txt
  json/Item_Weapon_Sword.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_TwinMachineGun.txt
  json/Item_Weapon_Wand.txt
  json/Item_Weapon_WiredLance.txt
Labels: size/L
