Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2022-12, with the labels that each got.

#417 Update Item_Addon_Unit.txt
  json/Item_Addon_Unit.txt
Labels: size/XS

#416 Select Ticket update
  json/Item_Stack_GachaTradePass.txt
Labels: size/M

#418 CN: Fix problems
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_Stack_GatCMatVegetable.txt
  json/Item_Stack_GatFMatFish.txt
  json/Items_Leftovers.txt
Labels: size/S
