Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2023-06, with the labels that each got.

#446 Select Ticket Update
  json/Item_Stack_GachaTradePass.txt
Labels: size/M

#448 EN: Update the Description Tool
  _tools/TicketDescriptions.py
Labels: size/L

#449 fix json format
  json/Item_NGS_BuildParts.txt
  json/Item_Stack_Music.txt
Labels: size/XS

#450 CN: tidy fix & update BP file for test
  json/Item_AvatarWPN_Sword.txt
  json/Item_NGS_BuildParts.txt
  json/Item_RingL.txt
  json/Item_Stack_PaidPass.txt
Labels: size/XXL

#451 CN: bug fix
  json/Item_AvatarWPN_Sword.txt
  json/Item_NGS_BuildParts.txt
  json/Item_Stack_Orderitem.txt
Labels: size/XXL

#452 CN: minor update
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_NGS_BuildParts.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Stamps.txt
Labels: size/L
