Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2023-08, with the labels that each got.

#455 CN: fix json format
  json/Item_AvatarWPN_Sword.txt
  json/Item_NGS_BuildParts.txt
Labels: size/XS

#456 CN: Adjust the name of "*Ruine Elder Pain"; fix the marks
  json/Item_AvatarWPN_Sword.txt
  json/Item_Disk_TECCustDark.txt
  json/Item_Disk_TECCustFire.txt
  json/Item_Disk_TECCustIce.txt
  json/Item_Disk_TECCustLight.txt
  json/Item_Disk_TECCustThunder.txt
  json/Item_Disk_TECCustWind.txt
  json/Item_Disk_TECDark.txt
  json/Item_Disk_TECFire.txt
  json/Item_Disk_TECIce.txt
  json/Item_Disk_TECLight.txt
  json/Item_Disk_TECThunder.txt
  json/Item_Disk_TECWind.txt
  json/Item_NGS_BuildParts.txt
Labels: size/M

#458 Please check if the quotations on the Oshi no Ko ticket are correct
  json/Item_Stack_GachaTradePass.txt
Labels: size/L

#460 I somehow left out \nTarget Scratch: when I did these?
  json/Item_Stack_GachaTradePass.txt
Labels: size/M
