Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2023-10, with the labels that each got.

#461 EN: translation adjustments in the Description Tool; add 'Iron Will' …
  _tools/TicketDescriptions.py
  json/Items_Leftovers.txt
Labels: size/S

#463 EN: fix the comma issue
  json/Item_NGS_Parts_Female.txt
  json/Item_NGS_Parts_Male.txt
Labels: size/XS

#464 Generated PortableHolograms file
  json/Item_NGS_PortableHolograms.txt
Labels: size/L
