Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2023-02, with the labels that each got.

#420 new-ish camos + descriptions
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_DoubleSaber.txt
  json/Item_AvatarWPN_DualBlade.txt
  json/Item_AvatarWPN_Katana.txt
  json/Item_AvatarWPN_Knuckle.txt
  json/Item_AvatarWPN_Launcher.txt
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Rod.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_AvatarWPN_Talis.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_AvatarWPN_TwinMachineGun.txt
  json/Item_AvatarWPN_Wand.txt
  json/Item_AvatarWPN_WiredLance.txt
Labels: size/M

#423 Add NGS Tickets to Ticket Descriptions Tool; Adjust Chinese description
  _tools/TicketDescriptions.py
Labels: size/M

#425 EN: Add more Tickets to Descriptions Tool; Adjust Chinese Description
  _tools/TicketDescriptions.py
Labels: size/L

#426 EN: Update Description Tool: Mag Devices; Description Sorting
  _tools/TicketDescriptions.py
Labels: size/L

#427 Update Description Tool: Resort formats of LA extras; Add Japanese comments for reference
  _tools/TicketDescriptions.py
Labels: size/L

#428 EN: Tool: update the Chinese translation
  _tools/TicketDescriptions.py
Labels: size/S

#431 KO: Updates from EN
  _tools/TicketDescriptions.py
  _tools/TranslateDupes.py
  json/Awakening_Skill_Explain_Token.txt
  json/ChipExplain_ActiveExplain.txt
  json/ChipExplain_SupportExplain.txt
  json/Item_AvatarWPN_AssaultRifle.txt
  json/Item_AvatarWPN_Compoundbow.txt
  json/Item_AvatarWPN_TwinDagger.txt
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_FacePattern.txt
  json/Item_InnerWear_Female.txt
  json/Item_InnerWear_Male.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Ear.txt
  json/Item_NGS_Horn.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Mouth.txt
  json/Item_NGS_Outer_Female.txt
  json/Item_NGS_Outer_Male.txt
  json/Item_NGS_Parts_Female.txt
  json/Item_NGS_Parts_Male.txt
  json/Item_NGS_Stamps.txt
  json/Item_Stack_Accessory.txt
  json/Item_Stack_BodyPaint.txt
  json/Item_Stack_Eye.txt
  json/Item_Stack_EyeBrow.txt
  json/Item_Stack_EyeLash.txt
  json/Item_Stack_FacePaint.txt
  json/Item_Stack_Hairstyle.txt
  json/Item_Stack_ItemBag.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Roomgoods.txt
  json/Item_Stack_Sticker.txt
  json/Item_Stack_Voice.txt
  json/Item_Weapon_Compoundbow.txt
  json/Item_Weapon_DoubleSaber.txt
  json/Item_Weapon_GunSlash.txt
  json/Item_Weapon_Launcher.txt
  json/Item_Weapon_Partizan.txt
  json/Item_Weapon_Tact.txt
  json/Item_Weapon_Talis.txt
  json/Item_Weapon_TwinDagger.txt
  json/Item_Weapon_WiredLance.txt
  json/Items_Leftovers.txt
  json/Name_Chip_ExtraName.txt
Labels: size/XXL

#433 KO: Update files
  _tools/TicketDescriptions.py
  json/Item_AvatarWPN_Partizan.txt
  json/Item_AvatarWPN_Sword.txt
  json/Item_FacePattern.txt
  json/Item_NGS_CapsuleAbilities.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Parts_Female.txt
  json/Item_NGS_Parts_Male.txt
  json/Item_Stack_Boost.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_GachaTradePass.txt
  json/Item_Stack_GatCMatMineral.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_Music.txt
  json/Item_Stack_PaidPass.txt
  json/Item_Stack_Tool.txt
Labels: size/XXL

#432 EN: Update Korean text in TIcketDescriptions.py
  _tools/TicketDescriptions.py
Labels: size/M

#434 KO: Tickets
  json/Item_BaseWear_Female.txt
  json/Item_BaseWear_Male.txt
  json/Item_FacePattern.txt
  json/Item_NGS_Ear.txt
  json/Item_NGS_Horn.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Mouth.txt
  json/Item_NGS_Parts_Female.txt
  json/Item_NGS_Parts_Male.txt
  json/Item_NGS_Stamps.txt
  json/Item_Stack_DeviceHT.txt
  json/Item_Stack_Headparts.txt
  json/Item_Stack_LobbyAction.txt
  json/Item_Stack_Voice.txt
Labels: size/XXL

#435 EN: fix the length problem of Chinese translation
  _tools/TicketDescriptions.py
Labels: size/S

#437 Aegis Trigger Name Fix
  json/Item_Stack_Tool.txt
Labels: size/XS
