Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2024-06, with the labels that each got.

#493 CN: FIX!
  json/Item_AvatarWPN_Sword.txt
Labels: size/XS

#492 EN: Update TicketGenerate
  _tools/TicketGenerateFromGamefile.py
Labels: size/L

#494 Select Ticket Fixes and Updates
  json/Item_Stack_GachaTradePass.txt
Labels: size/XL
