Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2024-01, with the labels that each got.

#474 EN: Ticket tool update; add JP explain of Krolik Arms
  _tools/TicketDescriptions.py
  json/Item_NGS_Parts_Female.txt
Labels: size/M

#477 EN: (Update to Jan.11) generate NGS items based on game files; adjust the ticket tool
  _tools/TicketDescriptions.py
  json/Item_NGS_Backgrounds.txt
  json/Item_NGS_Ear.txt
  json/Item_NGS_Horn.txt
  json/Item_NGS_Motion.txt
  json/Item_NGS_Mouth.txt
  json/Item_NGS_Outer_Female.txt
  json/Item_NGS_Outer_Male.txt
Labels: size/L

#478 EN: Create Ticket Generator (issues fixed)
  _tools/TicketGenerateFromGamefile.py
Labels: size/XL

#479 Update TicketDescriptions.py
  _tools/TicketDescriptions.py
Labels: size/M

#481 Update TicketdescTool & TicketgenTool to adapt new patch
  _tools/TicketDescriptions.py
  _tools/TicketGenerateFromGamefile.py
Labels: size/M
