Repository Arks-Layer/PSO2esTranslations, pull requests merged in 2024-08, with the labels that each got.

#501 New scratch select tickets
  json/Item_Stack_GachaTradePass.txt
Labels: size/M

#499 EN: Update Ticket Generator to adapt new cards generation
  _tools/TicketDescriptions.py
  _tools/TicketGenerateFromGamefile.py
Labels: size/L

#502 Fix typo
  json/Item_Stack_GachaTradePass.txt
Labels: size/XS
